### PR TITLE
added SESSION_COOKIE_SECURE and CSRF_COOKIE_SAMESITE Strict

### LINKED ISSUE #240: Sicherere Cookie-Settings
Wir haben momentan gesetzt:

- `CSRF_COOKIE_HTTPONLY`
- `CSRF_COOKIE_SECURE` (ausser mit `DEBUG`)
- `SESSION_COOKIE_HTTPONLY`(implizit, ist default true)

Weitere Einstellungen die Django bietet:

- `CSRF_COOKIE_SAMESITE = 'strict'` - würde vermutlich Sinn machen
- `SESSION_COOKIE_SAMESITE = 'strict'` - vermutlich zu restriktiv. Wenn eine Benutzerin einen Link zum Studentenportal klickt, soll sie ja eingeloggt sein, wenn sie das vorher war.
- `SESSION_COOKIE_SECURE = True` - sollten wir IMHO definitiv setzen, analog zum CSRF-Cookie, oder?

Für Details zu HttpOnly/Secure/SameSite, siehe [dieses MDN-Dokument](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies).

### PR DESCRIPTION
**Pull request by Murthy10**
## Description
Added:
- SESSION_COOKIE_SECURE=true
- CSRF_COOKIE_SAMESITE='Strict'

Related to issue / closes #240

### CODE REVIEW

**Comment by dbrgn** [comment]
Are you sure that we want strict samesite mode?

https://docs.djangoproject.com/en/3.1/ref/settings/#session-cookie-samesite

That would meant hat if a user follows a link from open\hsr (or from webmail) while already logged in, then the session cookie will not be sent.

I think `Lax` should be fine.

**Comment by Murthy10** [comment]
> Are you sure that we want strict samesite mode?
> 
> https://docs.djangoproject.com/en/3.1/ref/settings/#session-cookie-samesite
> 
> That would meant hat if a user follows a link from open\hsr (or from webmail) while already logged in, then the session cookie will not be sent.
> 
> I think `Lax` should be fine.

@dbrgn thanks for your review / comment. 
For me 'Lax' is fine, too.
I'm in that case more the executive force, maybe @The-Compiler or @fabianhauser can add their opinion / intent.

**Comment by The-Compiler** [comment]
Like I mentioned in #240, I don't think we should set `SESSION_COOKIE_SAMESITE = 'strict'` - but this PR sets `CSRF_COOKIE_SAMESITE` which is not the same thing.

**Review by dbrgn — APPROVED** [review]
Ouch, sorry, I mixed up the two because the `CSRF_COOKIE_SAMESITE` docs link directly to `SESSION_COOKIE_SAMESITE` docs :slightly_smiling_face:

**Review by fabianhauser — APPROVED** [review]

**Pull request merged**
