### PR TITLE
Feature/issue 235 refactor rating

### PR DESCRIPTION
**Pull request by Murthy10**
## Description
Rating Refactoring.

Related to issue #235

### CODE REVIEW

**Review by fabianhauser — COMMENTED** [review]
- [x] The rating of (average) of 9.5 is displayed as "Durchschnitt 10,0/10" (either display without comma or round to 0.1 precision)
- [ ] Stars for dozenten-ratings are not displayed when user has not rated them yet:
image
(I expected the same behaviour as for documents: if not voted for yet, the current average is shown)
- [ ] If possible it would be nice to have less bright stars for average rating, so that it is visually clear whether I have given a rating or not. (This is a feature, so only if easily doable.)

**Comment by Murthy10** [comment]
> * [x]  The rating of (average) of 9.5 is displayed as "Durchschnitt 10,0/10" (either display without comma or round to 0.1 precision)
> * [ ]  Stars for dozenten-ratings are not displayed when user has not rated them yet:
>   image
>   (I expected the same behaviour as for documents: if not voted for yet, the current average is shown)
> * [ ]  If possible it would be nice to have less bright stars for average rating, so that it is visually clear whether I have given a rating or not. (This is a feature, so only if easily doable.)

**Lecturer**
Now for the Lecturer the numbers represent the average rating, whereas the right hand side represents your own rating (one users's)  as stars.

**Document**
In the case of documents there is always the average display as stars, not your own (one users's) rating (at least this is the case if you rate and afterwards reload the page).

@fabianhauser for sure this varying UI behavior is irritating and maybe we should unify it.
But which concept should we use, does a user expect?

**Comment by Murthy10** [comment]
Since UI experience of Documents and Lecturers in regards to rating was different and a little bit confusing, I'd like to introduce a new approach.

It looks like the following:

Lecturer
Screenshot from 2021-01-18 10-32-02

Documents
Screenshot from 2021-01-18 10-31-07

@fabianhauser what do you think about it?

**Comment by fabianhauser** [comment]
Looks like a great improvement!

How do you feel about swapping the order to *rating, average* and making the average formatted like `Ø 3/10 ⭐`? I think we could loose the titles then, too, as the meaning should be obvious.

**Comment by Murthy10** [comment]
> Looks like a great improvement!
> 
> How do you feel about swapping the order to _rating, average_ and making the average formatted like `Ø 3/10 ⭐`? I think we could loose the titles then, too, as the meaning should be obvious.

Sure, I will apply your suggested changes and add new screenshots that we can compare those.

**Comment by Murthy10** [comment]
Next proposal @fabianhauser what do you think about it?
(I personally kind of like the title since for me it was not clear that we have to deal with own rating and average rating)
Screenshot from 2021-01-19 19-35-51

**Review by fabianhauser — APPROVED** [review]
LGTM :+1:

**Pull request merged**
